name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flet-dev/build-flet-app-action@v1
        with:
          module_name: 'main.py'
          target: 'apk'
